// -------------------- /api/dailyReport.js --------------------
// Sends a daily Supabase usage summary email for Ready4Exam automation
// Uses Supabase_11 (shared) and Gmail SMTP via App Password
// Compatible with Vercel Cron or manual GET/POST trigger

import { createClient } from "@supabase/supabase-js";
import nodemailer from "nodemailer";
import { getCorsHeaders } from "./_cors.js";

export const config = { runtime: "nodejs" };

// Utility to get start of today's date in UTC
function startOfTodayISO() {
  const d = new Date();
  const yyyy = d.getUTCFullYear();
  const mm = String(d.getUTCMonth() + 1).padStart(2, "0");
  const dd = String(d.getUTCDate()).padStart(2, "0");
  return `${yyyy}-${mm}-${dd}T00:00:00Z`;
}

export default async function handler(req, res) {
  const origin = req.headers?.origin || "*";
  const headers = { ...getCorsHeaders(origin), "Content-Type": "application/json" };
  Object.entries(headers).forEach(([k, v]) => res.setHeader(k, v));

  if (req.method === "OPTIONS") return res.status(200).end();
  if (!["GET", "POST"].includes(req.method)) {
    return res.status(405).json({ error: "Only GET or POST allowed" });
  }

  try {
    // --- ENV VALIDATION ---
    const SUPABASE_URL = process.env.SUPABASE_URL_11;
    const SUPABASE_KEY = process.env.SUPABASE_SERVICE_KEY_11;
    const SMTP_HOST = process.env.SMTP_HOST;
    const SMTP_PORT = process.env.SMTP_PORT;
    const SMTP_USER = process.env.SMTP_USER;
    const SMTP_PASS = process.env.SMTP_PASS;
    const TO_EMAIL = process.env.DAILY_REPORT_EMAIL;
    const FROM_EMAIL = process.env.REPORT_FROM_EMAIL || SMTP_USER;

    console.log("🧩 ENV CHECK:", {
      SUPABASE_URL: !!SUPABASE_URL,
      SUPABASE_KEY: !!SUPABASE_KEY,
      SMTP_HOST: !!SMTP_HOST,
      SMTP_PORT: !!SMTP_PORT,
      SMTP_USER: !!SMTP_USER,
      SMTP_PASS: !!SMTP_PASS,
      TO_EMAIL: !!TO_EMAIL,
    });

    if (!SUPABASE_URL || !SUPABASE_KEY) throw new Error("Supabase_11 credentials missing");
    if (!SMTP_HOST || !SMTP_PORT || !SMTP_USER || !SMTP_PASS) throw new Error("SMTP credentials missing");
    if (!TO_EMAIL) throw new Error("DAILY_REPORT_EMAIL missing");

    const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);
    const since = startOfTodayISO();

    // --- FETCH TODAY'S USAGE LOGS ---
    const { data: rows, error: queryError } = await supabase
      .from("usage_logs")
      .select("class_name,subject,book,chapter,table_name,inserted_count,refresh,created_at")
      .gte("created_at", since)
      .order("created_at", { ascending: false });

    if (queryError) throw new Error("Supabase query error: " + queryError.message);

    // --- AGGREGATE METRICS ---
    const totalRuns = rows?.length || 0;
    const distinctTables = new Set(rows.map(r => r.table_name)).size;
    const totalInserted = rows.reduce((s, r) => s + (Number(r.inserted_count) || 0), 0);
    const top = [...rows]
      .filter(r => r.inserted_count)
      .sort((a, b) => (b.inserted_count || 0) - (a.inserted_count || 0))
      .slice(0, 10);

    const today = since.slice(0, 10);
    const now = new Date().toISOString();

    // --- EMAIL CONTENT ---
    const htmlRows = top.length
      ? top.map(r => `
        <tr>
          <td>${r.class_name}</td>
          <td>${r.subject}</td>
          <td>${r.book || "-"}</td>
          <td>${r.chapter}</td>
          <td>${r.table_name}</td>
          <td style="text-align:right">${r.inserted_count}</td>
        </tr>`).join("\n")
      : `<tr><td colspan="6" style="text-align:center;padding:12px;">No new inserts recorded today</td></tr>`;

    const html = `
      <div style="font-family:Arial,Helvetica,sans-serif;color:#111">
        <h2>📊 Ready4Exam – Daily Supabase Usage Report</h2>
        <p><strong>Date (UTC):</strong> ${today}</p>
        <p><strong>Generated at:</strong> ${now}</p>
        <ul>
          <li><strong>Total Runs:</strong> ${totalRuns}</li>
          <li><strong>Distinct Tables Updated:</strong> ${distinctTables}</li>
          <li><strong>Total Questions Inserted:</strong> ${totalInserted}</li>
        </ul>

        <h3>Top Chapters (Most Recent Activity)</h3>
        <table width="100%" border="1" cellspacing="0" cellpadding="6" style="border-collapse:collapse;border:1px solid #ddd">
          <thead style="background:#f5f5f5">
            <tr>
              <th>Class</th><th>Subject</th><th>Book</th><th>Chapter</th><th>Table</th><th>Inserted</th>
            </tr>
          </thead>
          <tbody>${htmlRows}</tbody>
        </table>

        <p style="margin-top:16px;font-size:12px;color:#555;">
          This report is auto-generated by <strong>ready4exam-master-automation</strong>.<br>
          Supabase instance: <code>Supabase_11</code>.
        </p>
      </div>
    `;

    // --- SMTP CONFIG ---
    const transporter = nodemailer.createTransport({
      host: SMTP_HOST,
      port: Number(SMTP_PORT),
      secure: true, // Gmail uses SSL on port 465
      auth: {
        user: SMTP_USER,
        pass: SMTP_PASS,
      },
    });

    // --- SEND EMAIL ---
    const mailOptions = {
      from: FROM_EMAIL,
      to: TO_EMAIL,
      subject: `[Ready4Exam] Daily Supabase Usage – ${today}`,
      html,
    };

    const info = await transporter.sendMail(mailOptions);
    console.log("✅ Email sent:", info?.messageId || info);

    // --- RESPONSE ---
    return res.status(200).json({
      ok: true,
      date: today,
      totalRuns,
      distinctTables,
      totalInserted,
      topCount: top.length,
      emailSent: TO_EMAIL,
      messageId: info?.messageId || null,
    });

  } catch (err) {
    console.error("❌ dailyReport.js error:", err);
    return res.status(500).json({ ok: false, error: err.message || String(err) });
  }
}
